version: "3.8"
services:
  web:
    build: ./frontend
    depends_on:
      - Backend
    ports:
      - "8080:3000"
    networks:
      - network-frontend
  Backend:
    build: ./backend
    depends_on:
      - mongo
    ports:
      - "5000:5000"  
    networks:
     - network-frontend
     - network-backend
  
  mongo:
    image: mongo
    restart: always
    volumes: 
      - mongodb_data:/data/db
    environment: 
      MONGODB_INITDB_ROOT_USERNAME: username
      MONGODB_INITDB_ROOT_PASSWORD: password
    networks: 
     - network-backend

networks:
  network-frontend:
  network-backend:

volumes: 
  mongodb_data:
